name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .
      - name: Format check (black)
        run: |
          pip install black
          black --check .
      - name: Run tests
        run: |
          pytest --cov=src/finance_capstone --cov-report=term-missing
      - name: Security (pip-audit)
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt || true
